import type { Metadata } from "next";
// 1. Cambia la importación a Roboto
import { Roboto, Geist_Mono } from "next/font/google";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";

// 2. Configura Roboto con sus subsets y weights
const roboto = Roboto({
  variable: "--font-roboto",
  subsets: ["latin"],
  weight: ["300", "400", "500", "700"], // Elige los grosores que uses (light, regular, medium, bold)
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // 3. Añade la variable de roboto a la clase html
      className={`${roboto.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 4. Aplica la fuente roboto por defecto en el body */}
      <body className="font-sans min-h-full flex flex-col">
        {children}
        <Toaster />
      </body>
    </html>
  );
}
